name: MTT
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - certifi=2025.10.5
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - click=7.1.2
  - colorama=0.4.4
  - configparser=5.2.0
  - cryptography=36.0.0
  - cudatoolkit=11.3.1
  - dataclasses=0.8
  - docker-pycreds=0.4.0
  - ffmpeg=4.3
  - freetype=2.11.0
  - giflib=5.2.1
  - gitdb=4.0.9
  - gitpython=3.1.27
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.3
  - intel-openmp=2021.4.0
  - jpeg=9d
  - kornia=0.6.3
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libpng=1.6.37
  - libprotobuf=3.15.8
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.7.3
  - numpy=1.21.2
  - numpy-base=1.21.2
  - openh264=2.1.1
  - openssl=1.1.1w
  - packaging=21.3
  - pathtools=0.1.2
  - pillow=9.0.1
  - pip=21.2.4
  - promise=2.3
  - protobuf=3.15.8
  - psutil=5.8.0
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.7
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch=1.11.0
  - pytorch-mutex=1.0
  - pyyaml=5.4.1
  - readline=8.1.2
  - requests=2.27.1
  - scipy=1.7.3
  - sentry-sdk=1.5.7
  - setproctitle=1.2.2
  - setuptools=58.0.4
  - shortuuid=1.0.8
  - six=1.16.0
  - smmap=3.0.5
  - sqlite=3.38.0
  - termcolor=1.1.0
  - tk=8.6.11
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - tqdm=4.67.1
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - urllib3=1.26.8
  - wandb=0.12.11
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - yaspin=2.1.0
  - zlib=1.2.11
  - zstd=1.4.9
